# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Download Visual Studio Installer Projects extension
      run: |
        $ProgressPreference = "silentlyContinue"; Invoke-WebRequest https://visualstudioclient.gallerycdn.vsassets.io/extensions/visualstudioclient/microsoftvisualstudio2017installerprojects/0.9.8/1588102164123/InstallerProjects.vsix -OutFile InstallerProjects.vsix

    - name: Install Visual Studio Installer Projects extension
      run: |
        & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe" /quiet InstallerProjects.vsix
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      
    - name: Restore solution NuGet packages
      run: nuget restore Solutions\Installer.sln
      
    - name: Build solution
      run: msbuild Solutions\Installer.sln /p:Configuration=Release
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: LoopCheckTool-Installer.msi
        path: LoopCheckTool.Installer\Release\LoopCheckTool.msi
        
